export const GLOBAL_AGENTS_MD = [
  "# User Communication Preferences",
  "",
  "- The user is tech savvy but is not a professional programmer.",
  "- Explain workflows in plain Portuguese first, then show commands or implementation details.",
  "- Avoid assuming CLI, Node, TypeScript, OpenCode, Gemini, MCP, sync, or agent jargon is obvious.",
  "- When a task has multiple tools or layers, describe the mental model before implementation details.",
  "- Prefer safe, reversible changes and clearly call out when something is generated versus the original source.",
  "",
  "# Memory, Rules, and Skills",
  "",
  "- Use this `AGENTS.md` for OpenCode-specific instructions only: OpenCode agent behavior, edit policy, and OGB workflow rules. Do not use it as the canonical long-term memory store unless the user explicitly asks for an OpenCode-only instruction.",
  "",
  "- Use canonical Gemini/OGB sources for durable memory, reusable rules, and reusable skills:",
  "  - Global user memory: macOS/Linux/WSL `~/.gemini/GEMINI.md`; Windows `%USERPROFILE%\\.gemini\\GEMINI.md` or `$env:USERPROFILE\\.gemini\\GEMINI.md`.",
  "  - Project memory: `./GEMINI.md`, only for this repository.",
  "  - Skills: the canonical Gemini/OGB skill source, not generated OpenCode copies.",
  "",
  "- If a canonical source is an index that imports or references more specific files, edit the most specific source file instead of the root/index file. This applies to `GEMINI.md` imports, skill `SKILL.md` files, and skill assets/references.",
  "",
  "- Treat `.opencode/generated/*` and generated `.opencode/skills/*` as projection output. Never edit them as the source of truth unless the user explicitly requests an OpenCode-only change.",
  "",
  "- When the user says “remember this”, “save this”, or gives a durable preference without scope, default to global Gemini memory unless it is clearly project-specific.",
  "- Never store secrets, tokens, credentials, private keys, or sensitive personal data in memory files.",
  "",
  "- Before creating a new skill, check for an existing skill with the same name or purpose.",
  "- Create reusable skills in the canonical Gemini/OGB source layer unless the user explicitly requests an experimental OpenCode-only skill.",
  "- If creating an OpenCode-only skill in `.opencode/skills/<name>/SKILL.md`, tell the user it does not automatically sync back to Gemini.",
  "",
  "- After changing any canonical memory, rule, or skill source, run or recommend `ogb sync`.",
  "- After larger changes or new skills, run or recommend `ogb doctor` or `ogb pass` to verify projection and conflicts.",
  "",
  "- If `AGENTS.md`, global `GEMINI.md`, project `GEMINI.md`, and skill sources conflict, prefer the most specific canonical non-generated source. For unclear conflicts, stop and ask, or preview with `ogb bidirectional-sync --dry-run`.",
  "",
  "# Tool Preferences",
  "",
  "- Prefer the standard `bash` tool when PTY commands are denied or unstable; it usually has broader, more reliable permissions in this environment.",
  "- Remember that `--tui` may not render through captured `bash` output; commands such as `gemini-md-export` can automatically fall back to plain text mode.",
  "",
  "# OpenCode MCP Installation Notes",
  "",
  "- For OpenCode `1.14.x`, configure MCP servers in `~/.config/opencode/opencode.json` under the top-level `mcp` key, not `mcpServers`.",
  "- Local OpenCode MCP entries must use:",
  "  - `type: \"local\"`",
  "  - `command` as the complete argv array, e.g. `[\"npx\", \"-y\", \"package@latest\"]`",
  "  - `environment` for environment variables, not `env`",
  "  - `enabled: true`",
  "- Do not use the Gemini-style shape inside OpenCode config (`command: \"npx\"`, separate `args`, and `env`); OpenCode may silently drop those fields and keep only `enabled`.",
  "- Verify OpenCode MCP installs with:",
  "  - `opencode debug config` to confirm the resolved `mcp` entry still contains `type`, `command`, and `environment`",
  "  - `opencode mcp list` to confirm the server is listed and connected",
  "- Gemini CLI still uses the separate `~/.gemini/settings.json` shape with top-level `mcpServers`, `command`, `args`, and `env`.",
  "- Never store API keys or secrets directly in memory/rule files; examples should use placeholders such as `<API_KEY>`.",
].join("\n") + "\n";
