export const PLAN_READ_ONLY_BASH_PERMISSIONS: Record<string, "allow" | "ask" | "deny"> = {
  "*": "ask",
  "pwd": "allow",
  "ls*": "allow",
  "rg*": "allow",
  "grep*": "allow",
  "cat *": "allow",
  "sed -n *": "allow",
  "nl -ba *": "allow",
  "head *": "allow",
  "tail *": "allow",
  "wc *": "allow",
  "git status*": "allow",
  "git diff*": "allow",
  "git log*": "allow",
  "git show*": "allow",
  "git branch*": "allow",
  "git ls-files*": "allow",
  "git rev-parse*": "allow",
  "git push*": "deny",
  "git reset*": "deny",
  "git clean*": "deny",
  "rm *": "deny",
  "sudo *": "deny",
};
