export const PLAN_READ_ONLY_BASH_PERMISSIONS: Record<string, "allow" | "ask" | "deny"> = {
  "*": "ask",
  "pwd": "allow",
  "ls*": "allow",
  "rg*": "allow",
  "grep*": "allow",
  "cat *": "allow",
  "sed -n *": "allow",
  "nl -ba *": "allow",
  "head *": "allow",
  "tail *": "allow",
  "wc *": "allow",
  "stat *": "allow",
  "du *": "allow",
  "file *": "allow",
  "realpath *": "allow",
  "dirname *": "allow",
  "basename *": "allow",
  "jq *": "allow",
  "sort *": "allow",
  "uniq *": "allow",
  "comm *": "allow",
  "git status*": "allow",
  "git diff*": "allow",
  "git log*": "allow",
  "git show*": "allow",
  "git branch*": "allow",
  "git ls-files*": "allow",
  "git rev-parse*": "allow",
  "git grep*": "allow",
  "git ls-tree*": "allow",
  "git cat-file*": "allow",
  "git blame*": "allow",
  "git worktree list*": "allow",
  "git cherry -v*": "allow",
  "git merge-base*": "allow",
  "git stash list*": "allow",
  "git stash show*": "allow",
  "git remote -v": "allow",
  "git remote get-url*": "allow",
  "git describe*": "allow",
  "gh --version": "allow",
  "gh auth status*": "allow",
  "gh status*": "allow",
  "gh repo view*": "allow",
  "gh repo list*": "allow",
  "gh pr status*": "allow",
  "gh pr list*": "allow",
  "gh pr view*": "allow",
  "gh pr diff*": "allow",
  "gh pr checks*": "allow",
  "gh issue status*": "allow",
  "gh issue list*": "allow",
  "gh issue view*": "allow",
  "gh release list*": "allow",
  "gh release view*": "allow",
  "gh run list*": "allow",
  "gh run view*": "allow",
  "gh run watch*": "allow",
  "gh workflow list*": "allow",
  "gh workflow view*": "allow",
  "gh label list*": "allow",
  "gh milestone list*": "allow",
  "gh gist list*": "allow",
  "gh gist view*": "allow",
  "gh search repos*": "allow",
  "gh search issues*": "allow",
  "gh search prs*": "allow",
  "gh search code*": "allow",
  "gh api rate_limit*": "allow",
  "gh api repos/*": "allow",
  "gh api /repos/*": "allow",
  "gh api users/*": "allow",
  "gh api /users/*": "allow",
  "gh api orgs/*": "allow",
  "gh api /orgs/*": "allow",
  "gh api search/*": "allow",
  "gh api /search/*": "allow",
  "git push*": "deny",
  "git reset*": "deny",
  "git clean*": "deny",
  "gh api graphql*": "deny",
  "gh api *--method POST*": "deny",
  "gh api *--method PUT*": "deny",
  "gh api *--method PATCH*": "deny",
  "gh api *--method DELETE*": "deny",
  "gh api *-X POST*": "deny",
  "gh api *-X PUT*": "deny",
  "gh api *-X PATCH*": "deny",
  "gh api *-X DELETE*": "deny",
  "gh auth login*": "deny",
  "gh auth logout*": "deny",
  "gh auth refresh*": "deny",
  "gh auth setup-git*": "deny",
  "gh repo clone*": "deny",
  "gh repo create*": "deny",
  "gh repo delete*": "deny",
  "gh repo edit*": "deny",
  "gh repo fork*": "deny",
  "gh repo rename*": "deny",
  "gh repo sync*": "deny",
  "gh repo transfer*": "deny",
  "gh pr checkout*": "deny",
  "gh pr create*": "deny",
  "gh pr edit*": "deny",
  "gh pr close*": "deny",
  "gh pr reopen*": "deny",
  "gh pr merge*": "deny",
  "gh pr ready*": "deny",
  "gh pr review*": "deny",
  "gh pr comment*": "deny",
  "gh issue create*": "deny",
  "gh issue edit*": "deny",
  "gh issue close*": "deny",
  "gh issue reopen*": "deny",
  "gh issue comment*": "deny",
  "gh release create*": "deny",
  "gh release edit*": "deny",
  "gh release delete*": "deny",
  "gh release upload*": "deny",
  "gh run cancel*": "deny",
  "gh run delete*": "deny",
  "gh run rerun*": "deny",
  "gh workflow disable*": "deny",
  "gh workflow enable*": "deny",
  "gh workflow run*": "deny",
  "gh gist create*": "deny",
  "gh gist edit*": "deny",
  "gh gist delete*": "deny",
  "rm *": "deny",
  "sudo *": "deny",
};

export const PLAN_NATIVE_READ_PERMISSIONS: Record<"read" | "glob" | "grep" | "list", "allow"> = {
  read: "allow",
  glob: "allow",
  grep: "allow",
  list: "allow",
};
