import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { resolveProjectPaths } from "./paths.js";
import { OGB_VERSION } from "./types.js";

export interface AgentSyncAdoptionOptions {
  projectRoot?: string;
  homeDir?: string;
  json?: boolean;
}

export interface AgentSyncCandidate {
  tool: "gemini" | "opencode" | "codex" | "agents" | "rulesync";
  scope: "project" | "global";
  kind: "rules" | "skills" | "agents" | "commands" | "config";
  path: string;
  exists: boolean;
  recommendation: "sync" | "observe" | "ignore";
  reason: string;
}

export interface AgentSyncAdoptionReport {
  version: string;
  projectRoot: string;
  executable: {
    available: boolean;
    command?: string;
    version?: string;
  };
  candidates: AgentSyncCandidate[];
  recommendation: string[];
}

function commandVersion(command: string): string | undefined {
  const result = spawnSync(command, ["--version"], { encoding: "utf8" });
  if (result.error || result.status !== 0) return undefined;
  return (result.stdout || result.stderr).trim() || undefined;
}

function resolveAgentRulesSyncCommand(): AgentSyncAdoptionReport["executable"] {
  for (const command of ["agent-rules-sync", "agent-rules-sync-daemon", "ars"]) {
    const version = commandVersion(command);
    if (version !== undefined) return { available: true, command, version };
  }
  return { available: false };
}

function candidate(
  tool: AgentSyncCandidate["tool"],
  scope: AgentSyncCandidate["scope"],
  kind: AgentSyncCandidate["kind"],
  filePath: string,
  recommendation: AgentSyncCandidate["recommendation"],
  reason: string,
): AgentSyncCandidate {
  return {
    tool,
    scope,
    kind,
    path: filePath,
    exists: fs.existsSync(filePath),
    recommendation,
    reason,
  };
}

export function buildAgentSyncAdoptionReport(options: AgentSyncAdoptionOptions = {}): AgentSyncAdoptionReport {
  const paths = resolveProjectPaths(options.projectRoot, options.homeDir);
  const candidates: AgentSyncCandidate[] = [
    candidate("gemini", "project", "rules", path.join(paths.projectRoot, "GEMINI.md"), "sync", "Project-authored Gemini rules are user-owned and can be synchronized."),
    candidate("gemini", "global", "rules", path.join(paths.homeDir, ".gemini", "GEMINI.md"), "sync", "Global Gemini rules are user-owned and can seed other tools."),
    candidate("opencode", "project", "rules", path.join(paths.projectRoot, "AGENTS.md"), "observe", "OpenCode may read AGENTS.md, but ogb currently writes the expanded context instead."),
    candidate("opencode", "global", "rules", path.join(paths.homeDir, ".config", "opencode", "AGENTS.md"), "observe", "Global OpenCode rules should be adopted only after a dry-run diff."),
    candidate("codex", "global", "rules", path.join(paths.homeDir, ".codex", "AGENTS.md"), "observe", "Codex global rules are personal assistant instructions; sync only with explicit approval."),
    candidate("gemini", "global", "skills", path.join(paths.homeDir, ".gemini", "skills"), "sync", "User-owned Gemini skills can be synchronized."),
    candidate("opencode", "project", "skills", path.join(paths.projectRoot, ".opencode", "skills"), "observe", "This includes bridge-generated extension skills; avoid daemon writes over generated files."),
    candidate("codex", "global", "skills", path.join(paths.homeDir, ".codex", "skills"), "observe", "Codex skills have their own SKILL.md contract; sync only after mapping frontmatter."),
    candidate("gemini", "global", "commands", path.join(paths.homeDir, ".gemini", "commands"), "sync", "User-owned Gemini commands can be converted."),
    candidate("opencode", "project", "commands", path.join(paths.projectRoot, ".opencode", "commands"), "observe", "Bridge-generated commands should be regenerated by ogb sync, not daemon-edited."),
    candidate("rulesync", "project", "config", path.join(paths.projectRoot, "rulesync.jsonc"), "observe", "A dedicated rulesync config can document which paths are safe."),
  ];

  const recommendation = [
    "Start with dry-run adoption only; do not enable a background daemon on day one.",
    "Keep Gemini Extensions as upstream packages. Update them with Gemini CLI, then run ogb sync.",
    "Allow bidirectional sync only for user-owned rules/skills/commands, not generated .opencode files.",
    "Use newest-wins only after backups and conflict review are comfortable.",
  ];

  return {
    version: OGB_VERSION,
    projectRoot: paths.projectRoot,
    executable: resolveAgentRulesSyncCommand(),
    candidates,
    recommendation,
  };
}

export function runAgentSyncAdoption(options: AgentSyncAdoptionOptions = {}): AgentSyncAdoptionReport {
  const paths = resolveProjectPaths(options.projectRoot, options.homeDir);
  const report = buildAgentSyncAdoptionReport(options);

  fs.mkdirSync(path.dirname(paths.agentSyncAdoptionPath), { recursive: true });
  fs.writeFileSync(paths.agentSyncAdoptionPath, `${JSON.stringify(report, null, 2)}\n`, "utf8");

  if (options.json) {
    console.log(JSON.stringify(report, null, 2));
  } else {
    console.log("OpenCode Gemini Bridge Agent Rules Sync Adoption");
    console.log(`Project: ${report.projectRoot}`);
    console.log(`agent-rules-sync: ${report.executable.available ? `${report.executable.command}${report.executable.version ? ` (${report.executable.version})` : ""}` : "not found"}`);
    console.log("Candidates:");
    for (const item of report.candidates.filter((candidate) => candidate.exists)) {
      console.log(`- ${item.recommendation.toUpperCase()} ${item.tool}/${item.kind}: ${item.path}`);
    }
    console.log("Recommendation:");
    for (const item of report.recommendation) console.log(`- ${item}`);
  }

  return report;
}
