import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { OGB_VERSION, type GeminiImport } from "./types.js";

export interface FlattenOptions {
  input: string;
  output?: string;
  maxDepth?: number;
  write?: boolean;
  homeDir?: string;
}

export interface FlattenResult {
  content: string;
  input: string;
  output?: string;
  imports: GeminiImport[];
  warnings: string[];
  errors: string[];
}

function isWindowsAbsolute(p: string): boolean {
  return /^[A-Za-z]:[\\/]/.test(p);
}

export function resolveImportPath(raw: string, baseDir: string, homeDir = os.homedir()): string {
  let p = raw.trim();
  if ((p.startsWith("\"") && p.endsWith("\"")) || (p.startsWith("'") && p.endsWith("'"))) {
    p = p.slice(1, -1);
  }

  if (p.startsWith("~/") || p.startsWith("~\\")) return path.resolve(homeDir, p.slice(2));
  if (path.isAbsolute(p) || isWindowsAbsolute(p)) return path.normalize(p);
  return path.resolve(baseDir, p);
}

export function parseGeminiImportLine(line: string): string[] {
  const trimmed = line.trim();
  if (!trimmed.startsWith("@")) return [];

  const imports: string[] = [];
  let index = 0;

  while (index < trimmed.length) {
    while (/\s/.test(trimmed[index] ?? "")) index += 1;
    if (index >= trimmed.length) break;
    if (trimmed[index] !== "@") return [];
    index += 1;

    const quote = trimmed[index];
    let raw = "";

    if (quote === "\"" || quote === "'") {
      index += 1;
      const start = index;
      while (index < trimmed.length && trimmed[index] !== quote) index += 1;
      if (index >= trimmed.length) return [];
      raw = trimmed.slice(start, index);
      index += 1;
    } else {
      const start = index;
      while (index < trimmed.length && !/\s/.test(trimmed[index])) index += 1;
      raw = trimmed.slice(start, index);
    }

    if (!raw.toLowerCase().endsWith(".md")) return [];
    imports.push(raw);
  }

  return imports;
}

function isFenceToggle(line: string): boolean {
  return /^\s*(```|~~~)/.test(line);
}

function importComment(text: string): string {
  return ["", `<!-- OGB: ${text} -->`, ""].join("\n");
}

export function flattenGeminiMd(options: FlattenOptions): FlattenResult {
  const maxDepth = options.maxDepth ?? 10;
  const write = options.write ?? true;
  const homeDir = options.homeDir ?? os.homedir();
  const imports: GeminiImport[] = [];
  const warnings: string[] = [];
  const errors: string[] = [];

  function expand(file: string, depth: number, stack: string[]): string {
    const full = path.resolve(file);

    if (depth > maxDepth) {
      const message = `Max import depth reached at ${full}`;
      warnings.push(message);
      return importComment(message);
    }

    if (stack.includes(full)) {
      const message = `Skipped circular import: ${[...stack, full].join(" -> ")}`;
      warnings.push(message);
      return importComment(message);
    }

    if (!fs.existsSync(full)) {
      const message = `Missing import: ${full}`;
      warnings.push(message);
      return importComment(message);
    }

    const base = path.dirname(full);
    const lines = fs.readFileSync(full, "utf8").split(/\r?\n/);
    const out: string[] = ["", `<!-- OGB BEGIN: ${full} -->`, ""];
    let inFence = false;

    for (const line of lines) {
      if (isFenceToggle(line)) {
        inFence = !inFence;
        out.push(line);
        continue;
      }

      const rawImports = inFence ? [] : parseGeminiImportLine(line);
      if (rawImports.length === 0) {
        out.push(line);
        continue;
      }

      for (const raw of rawImports) {
        const target = resolveImportPath(raw, base, homeDir);
        const exists = fs.existsSync(target);
        const circular = stack.includes(path.resolve(target));
        const tooDeep = depth + 1 > maxDepth;
        const status = !exists || circular || tooDeep ? "warning" : "ok";
        imports.push({
          source: full,
          target,
          raw,
          depth: depth + 1,
          status,
          message: !exists
            ? "Missing import"
            : circular
              ? "Circular import"
              : tooDeep
                ? "Max depth reached"
                : undefined,
        });
        out.push(expand(target, depth + 1, [...stack, full]));
      }
    }

    out.push("", `<!-- OGB END: ${full} -->`, "");
    return out.join("\n");
  }

  const input = path.resolve(options.input);
  const header = [
    "# GENERATED BY OpenCode Gemini Bridge. DO NOT EDIT.",
    "",
    `Generator: ogb ${OGB_VERSION}`,
    `Source: ${input}`,
    "",
  ].join("\n");

  const content = header + expand(input, 0, []);

  if (write) {
    if (!options.output) throw new Error("flattenGeminiMd requires output when write is enabled");
    fs.mkdirSync(path.dirname(options.output), { recursive: true });
    fs.writeFileSync(options.output, content, "utf8");
  }

  return {
    content,
    input,
    output: options.output,
    imports,
    warnings,
    errors,
  };
}
