import fs from "node:fs";
import path from "node:path";
import { BUILT_IN_AGENTS, BUILT_IN_COMMANDS, REMOVED_BUILT_IN_AGENT_NAMES, REMOVED_BUILT_IN_COMMAND_NAMES, type BuiltInTextFile } from "./built-ins.js";
import { projectGeminiExtensionCommands } from "./extension-projection.js";
import { externalOpenCodePlugins, externalTuiPlugins, projectExternalIntegrations } from "./external-integrations.js";
import { buildInventory } from "./inventory.js";
import { readOgbConfig } from "./ogb-config.js";
import { defaultGeminiInput, resolveProjectPaths } from "./paths.js";
import { ensureProjectConfig } from "./project-config.js";
import { projectRulesyncProjection, type RulesyncMode, type RulesyncProjectionResult } from "./rulesync.js";
import { emptySyncState, managedHashFor, readSyncState, upsertManagedFile, writeSyncState } from "./sync-state.js";
import { ensureTuiSidebar } from "./tui-sidebar.js";
import { OGB_VERSION } from "./types.js";
import { sha256File } from "./file-hash.js";
import { flattenGeminiMd } from "./flatten.js";

export interface SyncOptions {
  projectRoot?: string;
  homeDir?: string;
  dryRun?: boolean;
  force?: boolean;
  rulesyncMode?: RulesyncMode;
  rulesyncFeatures?: string[];
}

export interface SyncReport {
  version: string;
  projectRoot: string;
  generatedConfigPath: string;
  projectedAgents: string[];
  projectedExtensionAgents: string[];
  projectedModelFallbackConfig?: string;
  projectedModelRoutingConfig?: string;
  removedAgents: string[];
  projectedCommands: string[];
  projectedExtensionCommands: string[];
  removedExtensionCommands: string[];
  projectedSkills: string[];
  projectedTuiFiles: string[];
  projectedExternalPlugins: string[];
  projectedExternalIntegrationFiles: string[];
  rulesync: RulesyncProjectionResult;
  warnings: string[];
}

function generatedOpenCodeConfig(projectRoot: string, homeDir?: string) {
  const inv = buildInventory({ projectRoot, homeDir });

  const mcp: Record<string, unknown> = {};
  for (const server of inv.mcps) {
    if (server.type === "stdio" && server.command) {
      const localServer: Record<string, unknown> = {
        type: "local",
        command: [server.command, ...(server.args ?? [])],
        enabled: true,
      };
      if (server.environment && Object.keys(server.environment).length > 0) {
        localServer.environment = server.environment;
      }
      mcp[server.name] = localServer;
    } else if (server.type === "http" && server.url) {
      mcp[server.name] = {
        type: "remote",
        url: server.url,
        enabled: true,
      };
    }
  }

  return {
    $schema: "https://opencode.ai/config.json",
    _generated: {
      tool: "ogb",
      version: OGB_VERSION,
      warning: "DO NOT EDIT. Regenerate with ogb sync.",
    },
    instructions: [".opencode/generated/GEMINI.expanded.md"],
    mcp,
  };
}

function expandedContentBody(content: string): string {
  const lines = content.split(/\r?\n/);
  const markerIndex = lines.findIndex((line) => line.startsWith("<!-- OGB BEGIN:") || line.startsWith("<!-- OGB: Missing import:"));
  return (markerIndex >= 0 ? lines.slice(markerIndex) : lines).join("\n").trim();
}

function writeExpandedGeminiContext(options: { projectRoot: string; homeDir: string; output: string; dryRun?: boolean }): void {
  const inventory = buildInventory({ projectRoot: options.projectRoot, homeDir: options.homeDir });
  const inputs = inventory.geminiFiles.length > 0
    ? inventory.geminiFiles
    : [defaultGeminiInput(options.projectRoot, options.homeDir)];
  const sections = inputs.map((input) => flattenGeminiMd({
    input,
    write: false,
    homeDir: options.homeDir,
  }));
  const header = [
    "# GENERATED BY OpenCode Gemini Bridge. DO NOT EDIT.",
    "",
    `Generator: ogb ${OGB_VERSION}`,
    "Sources:",
    ...inputs.map((input) => `- ${input}`),
    "",
  ].join("\n");
  const content = `${header}${sections.map((section) => expandedContentBody(section.content)).join("\n\n")}\n`;

  if (!options.dryRun) {
    fs.mkdirSync(path.dirname(options.output), { recursive: true });
    fs.writeFileSync(options.output, content, "utf8");
  }
}

function safeSkillTargetName(name: string, used: Set<string>, extensionName: string): string {
  if (!used.has(name)) return name;
  let candidate = `${extensionName}-${name}`;
  let index = 2;
  while (used.has(candidate)) {
    candidate = `${extensionName}-${name}-${index}`;
    index += 1;
  }
  return candidate;
}

function listGeminiExtensionSkillDirs(homeDir: string): Array<{ extensionName: string; skillName: string; sourceDir: string }> {
  const extensionsRoot = path.join(homeDir, ".gemini", "extensions");
  if (!fs.existsSync(extensionsRoot)) return [];

  const out: Array<{ extensionName: string; skillName: string; sourceDir: string }> = [];
  for (const extensionName of fs.readdirSync(extensionsRoot).sort()) {
    const skillsRoot = path.join(extensionsRoot, extensionName, "skills");
    if (!fs.existsSync(skillsRoot)) continue;
    for (const entry of fs.readdirSync(skillsRoot, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
      if (!entry.isDirectory()) continue;
      const sourceDir = path.join(skillsRoot, entry.name);
      if (!fs.existsSync(path.join(sourceDir, "SKILL.md"))) continue;
      out.push({ extensionName, skillName: entry.name, sourceDir });
    }
  }
  return out;
}

function copyDir(src: string, dst: string): void {
  fs.rmSync(dst, { recursive: true, force: true });
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.cpSync(src, dst, { recursive: true });
}

function projectExtensionSkills(options: { projectRoot: string; homeDir: string; dryRun?: boolean; force?: boolean }): { promoted: string[]; warnings: string[] } {
  const extensionSkills = listGeminiExtensionSkillDirs(options.homeDir);
  const warnings: string[] = [];
  const promoted: string[] = [];
  const used = new Set<string>();
  const state = readSyncState(options.projectRoot) ?? emptySyncState(OGB_VERSION);

  for (const skill of extensionSkills) {
    const targetName = safeSkillTargetName(skill.skillName, used, skill.extensionName);
    used.add(targetName);
    const relPath = `.opencode/skills/${targetName}`;
    const targetDir = path.join(options.projectRoot, ".opencode", "skills", targetName);

    if (options.dryRun) {
      promoted.push(relPath);
      continue;
    }

    const previousHash = managedHashFor(state, `${relPath}/SKILL.md`, "ogb");
    const currentSkillFile = path.join(targetDir, "SKILL.md");
    if (fs.existsSync(targetDir) && !options.force && previousHash && fs.existsSync(currentSkillFile) && sha256File(currentSkillFile) !== previousHash) {
      warnings.push(`Skill conflict: ${relPath} was edited manually; use --force to overwrite`);
      continue;
    }

    if (fs.existsSync(targetDir) && !options.force && !previousHash) {
      warnings.push(`Skill conflict: ${relPath} exists and is not managed by ogb; use --force to overwrite`);
      continue;
    }

    copyDir(skill.sourceDir, targetDir);
    const copiedSkillFile = path.join(targetDir, "SKILL.md");
    upsertManagedFile(state, {
      path: `${relPath}/SKILL.md`,
      sha256: sha256File(copiedSkillFile),
      source: "ogb",
    });
    promoted.push(relPath);
  }

  if (!options.dryRun) writeSyncState(state, options.projectRoot);
  return { promoted, warnings };
}

function projectBuiltInFiles(options: {
  projectRoot: string;
  dryRun?: boolean;
  force?: boolean;
  relDir: ".opencode/agents" | ".opencode/commands";
  files: BuiltInTextFile[];
  label: "Agent" | "Command";
  removedNames?: string[];
}): { promoted: string[]; removed: string[]; warnings: string[] } {
  const warnings: string[] = [];
  const promoted: string[] = [];
  const removed: string[] = [];
  const state = readSyncState(options.projectRoot) ?? emptySyncState(OGB_VERSION);

  for (const removedName of options.removedNames ?? []) {
    const relPath = `${options.relDir}/${removedName}.md`;
    const targetPath = path.join(options.projectRoot, options.relDir, `${removedName}.md`);
    const previousHash = managedHashFor(state, relPath, "ogb");

    if (options.dryRun || !fs.existsSync(targetPath) || !previousHash) continue;
    if (!options.force && sha256File(targetPath) !== previousHash) {
      warnings.push(`${options.label} conflict: ${relPath} was edited manually; leaving obsolete file in place`);
      continue;
    }

    fs.rmSync(targetPath, { force: true });
    state.managedFiles = state.managedFiles.filter((file) => !(file.path === relPath && file.source === "ogb"));
    removed.push(relPath);
  }

  for (const file of options.files) {
    for (const legacyName of file.legacyNames ?? []) {
      const legacyRelPath = `${options.relDir}/${legacyName}.md`;
      const legacyPath = path.join(options.projectRoot, options.relDir, `${legacyName}.md`);
      const previousHash = managedHashFor(state, legacyRelPath, "ogb");

      if (options.dryRun || !fs.existsSync(legacyPath)) continue;
      if (!previousHash && !options.force) continue;

      if (!options.force && previousHash && sha256File(legacyPath) !== previousHash) {
        warnings.push(`${options.label} conflict: ${legacyRelPath} was edited manually; leaving legacy file in place`);
        continue;
      }

      fs.rmSync(legacyPath, { force: true });
      state.managedFiles = state.managedFiles.filter((file) => !(file.path === legacyRelPath && file.source === "ogb"));
    }

    const relPath = `${options.relDir}/${file.name}.md`;
    const targetPath = path.join(options.projectRoot, options.relDir, `${file.name}.md`);

    if (options.dryRun) {
      promoted.push(relPath);
      continue;
    }

    const previousHash = managedHashFor(state, relPath, "ogb");
    if (fs.existsSync(targetPath) && !options.force) {
      const currentHash = sha256File(targetPath);
      if (previousHash !== currentHash) {
        warnings.push(`${options.label} conflict: ${relPath} exists or was edited manually; use --force to overwrite`);
        continue;
      }
    }

    fs.mkdirSync(path.dirname(targetPath), { recursive: true });
    fs.writeFileSync(targetPath, file.content, "utf8");
    upsertManagedFile(state, {
      path: relPath,
      sha256: sha256File(targetPath),
      source: "ogb",
    });
    promoted.push(relPath);
  }

  if (!options.dryRun) writeSyncState(state, options.projectRoot);
  return { promoted, removed, warnings };
}

export function syncToOpenCode(options: SyncOptions = {}): SyncReport {
  const paths = resolveProjectPaths(options.projectRoot, options.homeDir);
  const ogbConfig = readOgbConfig(paths.projectRoot, paths.homeDir);
  const openCodePlugins = externalOpenCodePlugins(ogbConfig);
  const tuiPlugins = externalTuiPlugins(ogbConfig);
  writeExpandedGeminiContext({
    projectRoot: paths.projectRoot,
    homeDir: paths.homeDir,
    output: paths.expandedGeminiPath,
    dryRun: options.dryRun,
  });

  const generated = generatedOpenCodeConfig(paths.projectRoot, paths.homeDir);
  const mcp = generated.mcp as Record<string, unknown>;
  const warnings: string[] = [];

  if (options.dryRun) {
    console.log(JSON.stringify(generated, null, 2));
  } else {
    fs.mkdirSync(path.dirname(paths.generatedOpenCodeConfigPath), { recursive: true });
    fs.writeFileSync(paths.generatedOpenCodeConfigPath, `${JSON.stringify(generated, null, 2)}\n`, "utf8");

    const state = readSyncState(paths.projectRoot) ?? emptySyncState(OGB_VERSION);
    upsertManagedFile(state, {
      path: ".opencode/generated/opencode.generated.json",
      sha256: sha256File(paths.generatedOpenCodeConfigPath),
      source: "ogb",
    });
    writeSyncState(state, paths.projectRoot);

    const configResult = ensureProjectConfig({
      projectRoot: paths.projectRoot,
      force: options.force,
      mcp,
      plugins: openCodePlugins,
    });
    if (configResult.status === "conflict") warnings.push(configResult.message ?? "opencode.jsonc conflict");
  }

  const projectedSkills = projectExtensionSkills({
    projectRoot: paths.projectRoot,
    homeDir: paths.homeDir,
    dryRun: options.dryRun,
    force: options.force,
  });
  warnings.push(...projectedSkills.warnings);

  const projectedTui = ensureTuiSidebar({
    projectRoot: paths.projectRoot,
    dryRun: options.dryRun,
    force: options.force,
    extraPlugins: tuiPlugins,
  });
  warnings.push(...projectedTui.warnings);

  const rulesync = projectRulesyncProjection({
    projectRoot: paths.projectRoot,
    homeDir: paths.homeDir,
    mode: options.rulesyncMode ?? "auto",
    dryRun: options.dryRun,
    force: options.force,
    features: options.rulesyncFeatures,
  });

  if (rulesync.status === "skipped" && rulesync.skippedReason) warnings.push(rulesync.skippedReason);
  if (rulesync.status === "partial") warnings.push(rulesync.stderr || "Rulesync partially completed");
  if (rulesync.status === "error") {
    if (rulesync.conflicts.length > 0) warnings.push(`Rulesync conflicts: ${rulesync.conflicts.join(", ")}`);
    else warnings.push(rulesync.stderr || rulesync.skippedReason || "Rulesync failed");
  }

  const projectedAgents = projectBuiltInFiles({
    projectRoot: paths.projectRoot,
    dryRun: options.dryRun,
    force: options.force,
    relDir: ".opencode/agents",
    files: BUILT_IN_AGENTS,
    label: "Agent",
    removedNames: REMOVED_BUILT_IN_AGENT_NAMES,
  });
  warnings.push(...projectedAgents.warnings);

  const projectedCommands = projectBuiltInFiles({
    projectRoot: paths.projectRoot,
    dryRun: options.dryRun,
    force: options.force,
    relDir: ".opencode/commands",
    files: BUILT_IN_COMMANDS,
    label: "Command",
    removedNames: REMOVED_BUILT_IN_COMMAND_NAMES,
  });
  warnings.push(...projectedCommands.warnings);

  const projectedExtensionCommands = projectGeminiExtensionCommands({
    projectRoot: paths.projectRoot,
    homeDir: paths.homeDir,
    dryRun: options.dryRun,
    force: options.force,
  });
  warnings.push(...projectedExtensionCommands.warnings);

  const projectedExternalIntegrations = projectExternalIntegrations({
    projectRoot: paths.projectRoot,
    homeDir: paths.homeDir,
    config: ogbConfig,
    extensionMap: projectedExtensionCommands.map,
    dryRun: options.dryRun,
  });
  warnings.push(...projectedExternalIntegrations.warnings);

  const report: SyncReport = {
    version: OGB_VERSION,
    projectRoot: paths.projectRoot,
    generatedConfigPath: paths.generatedOpenCodeConfigPath,
    projectedAgents: projectedAgents.promoted,
    projectedExtensionAgents: projectedExtensionCommands.projectedAgents,
    projectedModelFallbackConfig: projectedExtensionCommands.projectedModelFallbackConfig,
    projectedModelRoutingConfig: projectedExtensionCommands.projectedModelRoutingConfig,
    removedAgents: projectedAgents.removed,
    projectedCommands: [...projectedCommands.promoted, ...projectedExtensionCommands.projectedCommands],
    projectedExtensionCommands: projectedExtensionCommands.projectedCommands,
    removedExtensionCommands: projectedExtensionCommands.removedCommands,
    projectedSkills: projectedSkills.promoted,
    projectedTuiFiles: [projectedTui.plugin, projectedTui.config]
      .filter((item) => item.status === "created" || item.status === "updated" || item.status === "preview")
      .map((item) => item.relPath),
    projectedExternalPlugins: [...new Set([...projectedExternalIntegrations.openCodePlugins, ...projectedExternalIntegrations.tuiPlugins])],
    projectedExternalIntegrationFiles: projectedExternalIntegrations.writes
      .filter((item) => item.status === "created" || item.status === "updated" || item.status === "preview")
      .map((item) => item.relPath),
    rulesync,
    warnings,
  };

  if (!options.dryRun) {
    const state = readSyncState(paths.projectRoot) ?? emptySyncState(OGB_VERSION);
    state.lastRulesync = {
      status: rulesync.status,
      command: rulesync.command,
      promoted: rulesync.promoted,
      conflicts: rulesync.conflicts,
      skippedReason: rulesync.skippedReason,
    };
    writeSyncState(state, paths.projectRoot);
  }

  console.log(`${options.dryRun ? "Would generate" : "Generated"} ${paths.generatedOpenCodeConfigPath}`);
  if (projectedAgents.promoted.length > 0) console.log(`${options.dryRun ? "Would project" : "Projected"} ${projectedAgents.promoted.length} built-in agent(s)`);
  if (projectedExtensionCommands.projectedAgents.length > 0) console.log(`${options.dryRun ? "Would project" : "Projected"} ${projectedExtensionCommands.projectedAgents.length} Gemini extension subagent(s)`);
  if (projectedExtensionCommands.projectedModelRoutingConfig) console.log(`${options.dryRun ? "Would project" : "Projected"} OGB model routing report`);
  if (projectedExtensionCommands.projectedModelFallbackConfig) console.log(`${options.dryRun ? "Would project" : "Projected"} compatibility model fallback config`);
  if (projectedExtensionCommands.removedAgents.length > 0) console.log(`Removed ${projectedExtensionCommands.removedAgents.length} stale Gemini extension subagent(s)`);
  if (projectedAgents.removed.length > 0) console.log(`Removed ${projectedAgents.removed.length} obsolete built-in agent(s)`);
  if (projectedCommands.promoted.length > 0) console.log(`${options.dryRun ? "Would project" : "Projected"} ${projectedCommands.promoted.length} built-in command(s)`);
  if (projectedExtensionCommands.projectedCommands.length > 0) console.log(`${options.dryRun ? "Would project" : "Projected"} ${projectedExtensionCommands.projectedCommands.length} Gemini extension command(s)`);
  if (projectedExtensionCommands.removedCommands.length > 0) console.log(`Removed ${projectedExtensionCommands.removedCommands.length} stale Gemini extension command(s)`);
  if (projectedSkills.promoted.length > 0) console.log(`${options.dryRun ? "Would project" : "Projected"} ${projectedSkills.promoted.length} Gemini extension skill(s)`);
  if (report.projectedTuiFiles.length > 0) console.log(`${options.dryRun ? "Would project" : "Projected"} ${report.projectedTuiFiles.length} TUI sidebar file(s)`);
  if (report.projectedExternalPlugins.length > 0) console.log(`${options.dryRun ? "Would enable" : "Enabled"} external plugin(s): ${report.projectedExternalPlugins.join(", ")}`);
  if (report.projectedExternalIntegrationFiles.length > 0) console.log(`${options.dryRun ? "Would project" : "Projected"} ${report.projectedExternalIntegrationFiles.length} external integration file(s)`);
  if (rulesync.status === "applied") console.log(`Rulesync promoted ${rulesync.promoted.length} file(s)`);
  if (rulesync.status === "partial") console.log(`Rulesync partially completed; promoted ${rulesync.promoted.length} file(s)`);
  if (rulesync.status === "preview") console.log("Rulesync dry-run completed");
  if (rulesync.status === "skipped") console.log(`Rulesync skipped: ${rulesync.skippedReason}`);
  if (rulesync.status === "error" && rulesync.conflicts.length > 0) console.log(`Rulesync conflicts: ${rulesync.conflicts.join(", ")}`);
  else if (rulesync.status === "error") console.log(`Rulesync failed: ${rulesync.stderr || rulesync.skippedReason || "unknown error"}`);

  if (options.rulesyncMode === "require" && rulesync.status === "error") process.exitCode = 2;
  if (options.rulesyncMode === "require" && rulesync.status === "partial") process.exitCode = 1;

  return report;
}
