param(
  [string]$InputPath = "GEMINI.md",
  [string]$OutputPath = ".opencode\generated\GEMINI.expanded.md",
  [int]$MaxDepth = 10
)

$ErrorActionPreference = "Stop"
$seen = New-Object 'System.Collections.Generic.HashSet[string]'

function Resolve-ImportPath {
  param([string]$RawPath, [string]$BaseDir)
  $p = $RawPath.Trim()
  if ($p.StartsWith("~/") -or $p.StartsWith("~\")) {
    $p = Join-Path $HOME $p.Substring(2)
  }
  if ([System.IO.Path]::IsPathRooted($p)) {
    return [System.IO.Path]::GetFullPath($p)
  }
  return [System.IO.Path]::GetFullPath((Join-Path $BaseDir $p))
}

function Expand-GeminiMd {
  param([string]$Path, [int]$Depth)

  if ($Depth -gt $MaxDepth) { return "`n<!-- OGB: max import depth reached at $Path -->`n" }

  $full = [System.IO.Path]::GetFullPath($Path)
  if ($seen.Contains($full)) { return "`n<!-- OGB: skipped circular import: $full -->`n" }
  if (-not (Test-Path $full)) { return "`n<!-- OGB: missing import: $full -->`n" }

  [void]$seen.Add($full)
  $base = Split-Path $full -Parent
  $out = New-Object System.Collections.Generic.List[string]
  $inFence = $false

  $out.Add("")
  $out.Add("<!-- OGB BEGIN: $full -->")
  $out.Add("")

  foreach ($line in Get-Content $full) {
    if ($line -match '^\s*(```|~~~)') {
      $inFence = -not $inFence
      $out.Add($line)
      continue
    }

    if (-not $inFence -and $line -match '^\s*(@(?:\.{1,2}[\\/]|~[\\/]|[A-Za-z]:[\\/]|/)[^\s]+\.md\s*)+$') {
      $matches = [regex]::Matches($line, '@(?<path>(?:\.{1,2}[\\/]|~[\\/]|[A-Za-z]:[\\/]|/)[^\s]+\.md)')
      foreach ($m in $matches) {
        $importPath = Resolve-ImportPath $m.Groups["path"].Value $base
        $out.Add((Expand-GeminiMd $importPath ($Depth + 1)))
      }
    } else {
      $out.Add($line)
    }
  }

  $out.Add("")
  $out.Add("<!-- OGB END: $full -->")
  $out.Add("")
  [void]$seen.Remove($full)
  return ($out -join [Environment]::NewLine)
}

$outDir = Split-Path $OutputPath -Parent
if ($outDir) { New-Item -ItemType Directory -Force $outDir | Out-Null }

$header = "# GENERATED BY OpenCode Gemini Bridge. DO NOT EDIT.`n`nSource: $([System.IO.Path]::GetFullPath($InputPath))`n`n"
$expanded = Expand-GeminiMd $InputPath 0
($header + $expanded) | Set-Content -Encoding UTF8 $OutputPath
Write-Host "Generated $OutputPath"
